debug: true
lore-enchantments-version: '0.0'
enchantments:
  volley:
    name: Volley
    type: VOLLEY
    max-level: 10
    arrow-exp: 'pow(2,L)'
    devia-exp: '3 * L'
  barrage:
    name: Barrage
    type: VOLLEY
    max-level: 10
    arrow-exp: 'pow(3,L) * F'
    devia-exp: '5 * F * L'
  tipped:
    name: Tipped
    type: TIPPED
    max-level: 10
  coated:
    name: Coated
    type: COATED
    max-level: 10
  flourish:
    name: Flourish
    type: FLOURISH
    max-level: 10
    exp: 'B * D * 0.25 * L'
  assassination:
    name: Assassination
    type: Assassination
    max-level: 10
    exp: 'B * (1 + (0.5 * L))'
    arc: 45
  celerity:
    name: Celerity
    type: CELERITY
    max-level: 10
    exp: 'B *(1 + (0.5 * L))'
  fire-critical:
    name: Fire Critical
    type: FIRE_CRITICAL
    max-level: 10
    exp: 'B * (1 + (0.5 * L))'
  shadow-step:
    name: Shadow Step
    type: SHADOW_STEP
    max-level: 10
    min-dist-exp: '0'
    max-dist-exp: '5 * L'
    behind-distance: 1
    action-type: RIGHT_CLICK
    sound:
      teleport: ENDERMAN_TELEPORT
  shadow-dance:
    name: Shadow Dance
    type: SHADOW_DANCE
    max-level: 10
    min-dist-exp: '0'
    max-dist-exp: '5 * L'
    behind-distance: 1
    action-type: SHIFT_RIGHT_CLICK
    sound:
      teleport: ENDERMAN_TELEPORT
  shadow-grip:
    name: Shadow Grip
    type: SHADOW_GRIP
    max-level: 10
    min-dist-exp: '0'
    max-dist-exp: '5 * L'
    front-distance: 1
    action-type: RIGHT_CLICK
    sound:
      teleport: ENDERMAN_TELEPORT
  explode:
    name: Explode
    type: EXPLODE
    max-level: 10
    power-exp: 2 * L
    action-type: RIGHT_CLICK
  explosive:
    name: Explosive
    type: EXPLOSIVE
    max-level: 10
    power-exp: 4 * L
  singlarity:
    name: Singlarity
    type: SINGLARITY
    max-level: 10
    min-dist-exp: '5'
    max-dist-exp: '5 * L'
    dispersion: 1
  wormhole:
    name: Wormhole
    type: WORMHOLE
    max-level: 10
    min-dist-exp: '5'
    max-dist-exp: '5 * L'
    dispersion: 1
    action-type: SHIFT_RIGHT_CLICK
    sound:
      teleport: ENDERMAN_TELEPORT
  recharging:
    name: Recharging
    type: RECHARGING
    sound:
      recharge-complete: LEVEL_UP
      recharge-pending: ANVIL_LAND
    show:
      amount: true
      durability: false
      tick: 20
  undroppable:
    name: Undroppable
    type: UNDROPPABLE
  immovable:
    name: Immovable
    type: IMMOVABLE
  bottleless:
    name: Bottomless
    type: BOTTOMLESS
  longshot:
    name: Long Shot
    type: DISTANCE_SHOT
    max-level: 10
    top-cap: false
    bot-cap: true
    damage-exp: "(L * D / 20) * B"
  shortshot:
    name: Short Shot
    type: DISTANCE_SHOT
    max-level: 10
    top-cap: false
    bot-cap: false
    damage-exp: "(L + 1 - (D / 10)) * B"
  knockup:
    name: Knock Up
    type: KNOCK_UP
    max-level: 10
    velocity-exp: "0.5 * L"
  charge:
    name: Charge
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: '0.35'
    parallel-exp: "L * B"
    aim-exp: "0"
    sound:
      leap: WITHER_SHOOT
  retreat:
    name: Retreat
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: '0.35'
    parallel-exp: "-L * B"
    aim-exp: "0"
    sound:
      leap: WITHER_SHOOT
  dart:
    name: Dart
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: '0'
    parallel-exp: '0'
    aim-exp: 'L * B'
    sound:
      leap: WITHER_SHOOT
  jump:
    name: Jump
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: "0.5 * L * B"
    parallel-exp: "0"
    aim-exp: "0"
    sound:
      leap: MAGMACUBE_JUMP
  doublejump:
    name: Double Jump
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: "0.5 * L * B"
    parallel-exp: "0"
    aim-exp: "0"
    reset-vertical: true
    sound:
      leap: MAGMACUBE_JUMP
  leap:
    name: Leap
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: "0.5 * L * B"
    parallel-exp: "0.5 * L * B"
    aim-exp: "0"
    sound:
      leap: MAGMACUBE_JUMP
  disengage:
    name: Disengage
    type: LEAP
    max-level: 10
    action-type: RIGHT_CLICK
    vertical-exp: "0.5 * L * B"
    parallel-exp: "-0.5 * L * B"
    aim-exp: "0"
    sound:
      leap: MAGMACUBE_JUMP
  command:
    name: Command
    type: COMMAND
  headshot:
    name: Headshot
    type: HEADSHOT
    exp: "B * (1 + (0.5 * L))"
    radius: 0.3
  injecting:
    name: Injecting
    type: INJECTING
    action-type: RIGHT_CLICK
    sound:
      inject: PISTON_EXTEND
  splashing:
    name: Splashing
    type: SPLASHING
    action-type: RIGHT_CLICK
    radius-exp: "5 * L"
    sound:
      inject: ZOMBIE_INFECT